name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

jobs:
  generate-snake:
    name: Generate GitHub contribution snake
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      # 1. Checkout the repository so the workflow can push to it later
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Generate both SVG & GIF contribution-snake animations
      - name: Generate snake animation
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: abhi963007          # change if you fork this repo
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      # 3. Push the generated files to the `output` branch (served by GitHub Pages)
      - name: Publish animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output               # branch where files will be pushed
          build_dir: dist                     # directory created by the previous step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
