name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force create dist with content
        run: |
          # Create directory
          mkdir -p dist
          
          # Create a simple SVG file
          cat > dist/github-contribution-grid-snake.svg << 'EOF'
          <svg width="800" height="400" xmlns="http://www.w3.org/2000/svg">
            <rect width="800" height="400" fill="#f6f8fa"/>
            <text x="400" y="200" text-anchor="middle" fill="#586069" font-family="Arial" font-size="16">
              GitHub Snake Animation Placeholder
            </text>
          </svg>
          EOF
          
          # Verify everything exists
          echo "Created files:"
          ls -la dist/
          
          # Check file contents
          echo "SVG file size: $(wc -c < dist/github-contribution-grid-snake.svg) bytes"
          
          # Verify directory is accessible
          cd dist
          pwd
          ls -la
          cd ..

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          allow_empty_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
